/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#e5e2e1",
        "inverse-surface": "#e4e2e1",
        "on-background": "#e4e2e1",
        "on-primary-container": "#7e7d7d",
        "on-primary-fixed-variant": "#474646",
        "on-tertiary-container": "#9b755c",
        "tertiary": "#eabda0",
        "on-secondary": "#2f3131",
        "surface-tint": "#c8c6c5",
        "surface-container-highest": "#353535",
        "primary-fixed-dim": "#c8c6c5",
        "on-secondary-fixed": "#1a1c1c",
        "background": "#131313",
        "surface-container-high": "#2a2a2a",
        "on-tertiary-fixed-variant": "#5f402a",
        "on-tertiary-fixed": "#2d1604",
        "surface-container": "#1f2020",
        "on-tertiary": "#452a16",
        "error-container": "#93000a",
        "surface-container-lowest": "#0e0e0e",
        "on-primary-fixed": "#1c1b1b",
        "surface-container-low": "#1b1c1c",
        "on-error": "#690005",
        "inverse-primary": "#5f5e5e",
        "error": "#ffb4ab",
        "surface-dim": "#131313",
        "tertiary-container": "#220c00",
        "surface": "#131313",
        "on-surface": "#e4e2e1",
        "on-surface-variant": "#c4c7c7",
        "secondary-fixed-dim": "#c6c6c7",
        "tertiary-fixed": "#ffdcc6",
        "surface-bright": "#393939",
        "secondary-fixed": "#e2e2e2",
        "tertiary-fixed-dim": "#eabda0",
        "secondary-container": "#454747",
        "inverse-on-surface": "#303030",
        "on-primary": "#313030",
        "secondary": "#c6c6c7",
        "surface-variant": "#353535",
        "primary-container": "#121212",
        "outline": "#8e9192",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#454747",
        "on-secondary-container": "#b4b5b5",
        "primary": "#c8c6c5",
        "outline-variant": "#444748"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "touch-target-min": "48px",
        "container-margin": "24px",
        "section-gap": "40px",
        "base": "8px",
        "gutter": "16px"
      }
    },
  },
  plugins: [],
}
